### ISSUE TITLE
Kommentar kring blocket-API

### ISSUE THREAD

**Issue by 1dv449** [jh222xk/netfynda#1]
Hejsan! Kollade igenom din beskrivning och såg du funderade på Blocket och att de saknar ett API. De är lite svåra på det men kanske det sätt som denna artikel tar upp kan vara något? 
http://www.mashup.se/nyheter/api-mandag-apfy-oppnadata-och-vinnova
Dock får man kanske fundera lite kring etiken på detta!?

**Comment by jh222xk** [comment]
Jag har nu pratat med Blocket och de säger att de har stängt ner sitt API som de hade innan på grund av att deras användare inte ville att deras annonser skulle publiceras på något annat ställe än Blocket. De har alltså stängt ner sitt API och har antiskrapningsmjukvara aktiv. 

Jag får alltså ingen officiell tillåtelse från Blocket att skrapa sajten.
